Repository TeamHous/Hous-iOS, pull requests merged in 2022-07, with the labels that each got.

#9 [#8] Feat: CustomTabbar 추가
  Hous-iOS/Hous-iOS.xcodeproj/project.pbxproj
  Hous-iOS/Hous-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hous-iOS/Hous-iOS/Global/Supports/SceneDelegate.swift
  Hous-iOS/Hous-iOS/Screens/Home/HomeViewController.swift
  Hous-iOS/Hous-iOS/Screens/Splash/SplashViewController.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbar.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbarItem.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbarItemView.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbarViewController.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/ViewController.swift
Labels: 호세🌈, Feat✨, Review required🍎, P0

#16 [#14] Refactor: Tabbar Detail 잡기
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbar.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbarItem.swift
  Hous-iOS/Hous-iOS/Screens/Tabbar/HousTabbarItemView.swift
Labels: 호세🌈, Feat✨, P0

#25 [#24] CHORE : Assignee color 리턴 다이나믹 컬러로 수정
  Hous-iOS/Hous-iOS/Global/Extension/UIColor+Extension.swift
Labels: 지현🏋🏻, HotFix🐞, Cleanup🗑

#30 [FEAT] Rules탭 카테고리 추가 뷰 레이아웃 및 뷰 연결
  Hous-iOS/Hous-iOS.xcodeproj/project.pbxproj
  Hous-iOS/Hous-iOS/Global/Extension/UIBezierPath+Extension.swift
  Hous-iOS/Hous-iOS/Global/Extension/UIColor+Extension.swift
  Hous-iOS/Hous-iOS/Global/Resource/Assets.xcassets/Common/laundry.imageset/Contents.json
  Hous-iOS/Hous-iOS/Global/Resource/Assets.xcassets/Common/laundry.imageset/ic_laundey.png
  Hous-iOS/Hous-iOS/Global/Resource/Assets.xcassets/Common/laundry.imageset/ic_laundey@2x.png
  Hous-iOS/Hous-iOS/Global/Resource/Assets.xcassets/Common/laundry.imageset/ic_laundey@3x.png
  Hous-iOS/Hous-iOS/Global/UIComponent/CategoryAssigneeCircleView.swift
  Hous-iOS/Hous-iOS/Global/UIComponent/NavigationBarView.swift
  Hous-iOS/Hous-iOS/Global/UIComponent/TodayTodoLeftRoundView.swift
  Hous-iOS/Hous-iOS/Screens/Profile/Cell/ProfileBadgeCollectionViewCell.swift
  Hous-iOS/Hous-iOS/Screens/Profile/Cell/ProfileInfoCollectionViewCell.swift
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileViewController.swift
  Hous-iOS/Hous-iOS/Screens/Rules/Cell/Todo/TodayTodoCollectionViewCell.swift
  Hous-iOS/Hous-iOS/Screens/Rules/Controller/RulesViewController.swift
  Hous-iOS/Hous-iOS/Screens/Rules/Enum/TodoTabEnum.swift
  Hous-iOS/Hous-iOS/Screens/Rules/View/RulesCategoryTableView.swift
  Hous-iOS/Hous-iOS/Screens/Rules/View/RulesCategoryView.swift
  Hous-iOS/Hous-iOS/Screens/Rules/View/RulesHomeView.swift
  Hous-iOS/Hous-iOS/Screens/Rules/View/RulesTodoTableView.swift
Labels: 지현🏋🏻, Feat✨, P0

#66 [#65] FIX : gitignore 수정
  Hous-iOS/Hous-iOS/Network/API/APIConstants.swift
Labels: 지현🏋🏻, HotFix🐞

#102 [#97] FEAT : Splash 추가
  Hous-iOS/Hous-iOS.xcodeproj/project.pbxproj
  Hous-iOS/Hous-iOS/Global/Resource/splashlottie.json
  Hous-iOS/Hous-iOS/Global/Supports/Launch Screen.storyboard
  Hous-iOS/Hous-iOS/Global/Supports/SceneDelegate.swift
  Hous-iOS/Hous-iOS/Screens/Splash/SplashViewController.swift
Labels: 민재🐣, P1, Feat✨

#105 [#101] FEAT : Rules by Category EmptyView
  Hous-iOS/Hous-iOS.xcodeproj/project.pbxproj
  Hous-iOS/Hous-iOS/Screens/Rules/Cell/Category/EmptyCategoryCollectionViewCell.swift
  Hous-iOS/Hous-iOS/Screens/Rules/View/RulesCategoryTableView.swift
Labels: 지현🏋🏻, P1, Feat✨

#109 [#106] FEAT : 규칙 생성 시 필요한 Target & Service
  Hous-iOS/Hous-iOS.xcodeproj/project.pbxproj
  Hous-iOS/Hous-iOS/Network/API/Rules/RulesCreateAPIService.swift
  Hous-iOS/Hous-iOS/Network/API/Rules/RulesCreateAPITarget.swift
  Hous-iOS/Hous-iOS/Network/Model/Rules/Todo.swift
  Hous-iOS/Hous-iOS/Network/Model/Rules/TodoCreate.swift
Labels: 지현🏋🏻, P1, Feat✨

#119 [#116] FIX : QA 수정사항 반영
  Hous-iOS/Hous-iOS/Screens/Home/ViewController/HomeViewController.swift
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileViewController.swift
Labels: 민재🐣, HotFix🐞

#120 [#117] DOCS : 리드미 수정 (지현)
  README.md
Labels: 지현🏋🏻, Docs📄, P2

#123 [#117] FEAT : 오늘의 Todo 담당자 제한
  Hous-iOS/Hous-iOS/Screens/Rules/Cell/Todo/TodayTodoCollectionViewCell.swift
Labels: 지현🏋🏻, P1, Feat✨

#127 [#125] FIX : 버그 수정
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileTestResultViewController.swift
  Hous-iOS/Hous-iOS/Screens/ProfileTest/ViewController/ProfileTestViewController.swift
Labels: 민재🐣, HotFix🐞

#129 [#114] FIX : 스크롤바 제거
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileTestResultViewController.swift
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileViewController.swift
Labels: P1, HotFix🐞, 의진🏄

#131 [#130] FIX : 결과 상세 페이지 UI 수정
  Hous-iOS/Hous-iOS/Screens/Profile/Controller/ProfileTestResultViewController.swift
Labels: HotFix🐞, 의진🏄, P0
